Repository TorXakis/TorXakis, pull requests merged in 2018-12, with the labels that each got.

#831 moved to right directory Adder iso adder
  examps/Adder/ReplayProc.txs
Labels: bug, documentation

#836 Allow Hidden Var by multi actions (not just ISTEP)
  sys/defs/src/TxsShow.hs
Labels: bug

#842 Fix wrong compiler error caused by unmatched parenthesis in function/constructor application
  README.md
  sys/txs-compiler/package.yaml
  sys/txs-compiler/src/TorXakis/Parser/Common.hs
  sys/txs-compiler/src/TorXakis/Parser/ValExprDecl.hs
  sys/txs-compiler/test/Common.hs
  sys/txs-compiler/test/TorXakis/CompilerSpec.hs
  sys/txs-compiler/test/TorXakis/ParserSpec.hs
  sys/txs-compiler/test/data/wrong/UnmatchedParenthesis.txs
Labels: component-txs-compiler
